package egovframework.let.platforms.factories.service.impl;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import egovframework.let.platforms.factories.service.FactoryRegistrationRequestVO;
import egovframework.let.platforms.factories.service.FactoryRegistrationResultVO;
import egovframework.let.platforms.factories.service.PlatformFactoryService;
import egovframework.let.platforms.factories.service.PlatformTenantDashboardItemVO;
import egovframework.let.platforms.factories.service.PlatformTenantDashboardQueryVO;
import egovframework.let.platforms.factories.service.PlatformTenantDashboardResultVO;
import egovframework.let.platforms.factories.service.PlatformTenantDashboardSummaryVO;
import egovframework.let.platforms.factories.service.SampleTenantVO;

@Service("platformFactoryService")
public class PlatformFactoryServiceImpl implements PlatformFactoryService {

    private final JdbcTemplate jdbcTemplate;

    public PlatformFactoryServiceImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    @Transactional
    public FactoryRegistrationResultVO registerFactory(FactoryRegistrationRequestVO requestVO) {
        validateRequest(requestVO);

        String factoryNm = requestVO.getFactoryNm().trim();
        String adminEmail = emptyToNull(requestVO.getAdminEmail());
        String corporateNumber = emptyToNull(requestVO.getCorporateNumber());
        String businessType = emptyToNull(requestVO.getBusinessType());
        String businessCategory = emptyToNull(requestVO.getBusinessCategory());

        // concurrent 등록 시 중복코드 충돌을 피하기 위해 제한된 횟수로 재시도한다.
        for (int attempt = 0; attempt < 5; attempt++) {
            String maxCode = jdbcTemplate.queryForObject(
                    "SELECT COALESCE(MAX(factory_code), '000000') FROM tb_factoryinfo WHERE factory_code ~ '^[0-9]{6}$'",
                    String.class
            );

            String factoryCode = FactoryCodeGenerator.nextFactoryCode(maxCode);
            String tenantCode = "TENANT_" + factoryCode;

            try {
                jdbcTemplate.update(
                        "INSERT INTO tb_factoryinfo (factory_code, factory_nm, tenant_code, admin_email, corporate_number, business_type, business_category) VALUES (?, ?, ?, ?, ?, ?, ?)",
                        factoryCode,
                        factoryNm,
                        tenantCode,
                        adminEmail,
                        corporateNumber,
                        businessType,
                        businessCategory
                );

                FactoryRegistrationResultVO resultVO = new FactoryRegistrationResultVO();
                resultVO.setFactoryCode(factoryCode);
                resultVO.setFactoryNm(factoryNm);
                resultVO.setTenantCode(tenantCode);
                resultVO.setAdminEmail(adminEmail);
                resultVO.setCorporateNumber(corporateNumber);
                resultVO.setBusinessType(businessType);
                resultVO.setBusinessCategory(businessCategory);
                resultVO.setCreatedAt(Instant.now().toString());
                return resultVO;
            } catch (DuplicateKeyException ex) {
                // duplicate factory code generated by concurrent insert. retry.
            }
        }

        throw new IllegalStateException("Unable to generate unique factory code");
    }

    @Override
    public PlatformTenantDashboardResultVO listDashboardTenants(
            PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO condition = normalizeQuery(queryVO);

        List<Object> whereParams = new ArrayList<Object>();
        String whereClause = buildWhereClause(condition, whereParams);

        int total = queryForCount(whereClause, whereParams, null);
        int active = queryForCount(whereClause, whereParams, "Y");
        int inactive = queryForCount(whereClause, whereParams, "N");

        List<Object> itemParams = new ArrayList<Object>(whereParams);
        itemParams.add(condition.getPageSize());
        itemParams.add(condition.getPageIndex() * condition.getPageSize());

        List<PlatformTenantDashboardItemVO> items = jdbcTemplate.query(
                "SELECT tenant_code, factory_nm, admin_email, use_at, created_at, corporate_number, business_type, business_category "
                        + "FROM tb_factoryinfo "
                        + whereClause
                        + " ORDER BY created_at DESC LIMIT ? OFFSET ?",
                itemParams.toArray(),
                (rs, rowNum) -> {
                    PlatformTenantDashboardItemVO item = new PlatformTenantDashboardItemVO();
                    item.setTenantCode(rs.getString("tenant_code"));
                    item.setCompanyName(rs.getString("factory_nm"));
                    item.setAdminName("-");
                    item.setAdminEmail(defaultDash(rs.getString("admin_email")));
                    item.setStatus("Y".equalsIgnoreCase(rs.getString("use_at")) ? "ACTIVE" : "INACTIVE");

                    Timestamp createdAt = rs.getTimestamp("created_at");
                    item.setCreatedAt(createdAt == null ? null : createdAt.toInstant().toString());

                    item.setCorporateNumber(rs.getString("corporate_number"));
                    item.setBusinessType(rs.getString("business_type"));
                    item.setBusinessCategory(rs.getString("business_category"));
                    return item;
                }
        );

        PlatformTenantDashboardSummaryVO summary = new PlatformTenantDashboardSummaryVO();
        summary.setTotal(total);
        summary.setActive(active);
        summary.setInactive(inactive);

        PlatformTenantDashboardResultVO result = new PlatformTenantDashboardResultVO();
        result.setSummary(summary);
        result.setItems(items);
        return result;
    }

    @Override
    public List<SampleTenantVO> listRecentTenants(int limit) {
        int safeLimit = limit <= 0 ? 5 : Math.min(limit, 50);

        return jdbcTemplate.query(
                "SELECT tenant_code, factory_nm, corporate_number, admin_email, created_at "
                        + "FROM tb_factoryinfo ORDER BY created_at DESC LIMIT ?",
                new Object[] { safeLimit },
                (rs, rowNum) -> {
                    SampleTenantVO item = new SampleTenantVO();
                    item.setTenantCode(rs.getString("tenant_code"));
                    item.setCompanyName(rs.getString("factory_nm"));
                    item.setBusinessRegistrationNumber(rs.getString("corporate_number"));
                    item.setAdminEmail(defaultDash(rs.getString("admin_email")));

                    Timestamp createdAt = rs.getTimestamp("created_at");
                    item.setIssuedAt(createdAt == null ? null : createdAt.toInstant().toString());
                    return item;
                }
        );
    }

    private int queryForCount(String whereClause, List<Object> whereParams, String useAtOnly) {
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM tb_factoryinfo ");
        List<Object> params = new ArrayList<Object>(whereParams);

        if (whereClause == null || whereClause.isEmpty()) {
            sql.append("WHERE 1=1");
        } else {
            sql.append(whereClause);
        }

        if (useAtOnly != null) {
            sql.append(" AND use_at = ?");
            params.add(useAtOnly);
        }

        Integer count = jdbcTemplate.queryForObject(sql.toString(), params.toArray(), Integer.class);
        return count == null ? 0 : count.intValue();
    }

    private PlatformTenantDashboardQueryVO normalizeQuery(PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO normalized = new PlatformTenantDashboardQueryVO();
        if (queryVO == null) {
            return normalized;
        }

        normalized.setPageIndex(Math.max(0, queryVO.getPageIndex()));
        int pageSize = queryVO.getPageSize();
        if (pageSize <= 0) {
            pageSize = 10;
        }
        if (pageSize > 100) {
            pageSize = 100;
        }
        normalized.setPageSize(pageSize);
        normalized.setSearchField(emptyToNull(queryVO.getSearchField()));
        normalized.setSearchKeyword(emptyToNull(queryVO.getSearchKeyword()));
        normalized.setStatus(emptyToNull(queryVO.getStatus()) == null ? "all" : queryVO.getStatus().trim());
        return normalized;
    }

    private String buildWhereClause(PlatformTenantDashboardQueryVO queryVO, List<Object> params) {
        StringBuilder where = new StringBuilder("WHERE 1=1");

        if (queryVO.getSearchKeyword() != null) {
            String keyword = "%" + queryVO.getSearchKeyword().trim() + "%";
            String searchField = queryVO.getSearchField();

            if ("tenantCode".equals(searchField)) {
                where.append(" AND tenant_code ILIKE ?");
                params.add(keyword);
            } else if ("adminName".equals(searchField)) {
                where.append(" AND COALESCE(admin_email, '') ILIKE ?");
                params.add(keyword);
            } else {
                where.append(" AND factory_nm ILIKE ?");
                params.add(keyword);
            }
        }

        if ("ACTIVE".equalsIgnoreCase(queryVO.getStatus())) {
            where.append(" AND use_at = 'Y'");
        } else if ("INACTIVE".equalsIgnoreCase(queryVO.getStatus())) {
            where.append(" AND use_at = 'N'");
        }

        return where.toString();
    }

    private void validateRequest(FactoryRegistrationRequestVO requestVO) {
        if (requestVO == null || requestVO.getFactoryNm() == null || requestVO.getFactoryNm().trim().isEmpty()) {
            throw new IllegalArgumentException("factoryNm is required");
        }
    }

    private String emptyToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String defaultDash(String value) {
        if (value == null || value.trim().isEmpty()) {
            return "-";
        }
        return value;
    }
}
