package egovframework.let.platforms.factories.service.impl;

import java.time.Instant;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import egovframework.let.platforms.factories.domain.model.FactoryRegistrationRequestVO;
import egovframework.let.platforms.factories.domain.model.FactoryRegistrationResultVO;
import egovframework.let.platforms.factories.domain.model.PlatformTenantDashboardItemVO;
import egovframework.let.platforms.factories.domain.model.PlatformTenantDashboardQueryVO;
import egovframework.let.platforms.factories.domain.model.PlatformTenantDashboardResultVO;
import egovframework.let.platforms.factories.domain.model.PlatformTenantDashboardSummaryVO;
import egovframework.let.platforms.factories.domain.model.SampleTenantVO;
import egovframework.let.platforms.factories.domain.repository.FactoryInfoDAO;
import egovframework.let.platforms.factories.service.PlatformFactoryService;

/**
 * 플랫폼 공장 서비스 구현체
 * @author AI Assistant
 * @since 2026.06.22
 * @version 1.0
 */
@Service("platformFactoryService")
public class PlatformFactoryServiceImpl implements PlatformFactoryService {

    @Resource(name = "factoryInfoDAO")
    private FactoryInfoDAO factoryInfoDAO;

    @Override
    @Transactional
    public FactoryRegistrationResultVO registerFactory(FactoryRegistrationRequestVO requestVO) {
        validateRequest(requestVO);

        String factoryNm = requestVO.getFactoryNm().trim();
        String adminEmail = emptyToNull(requestVO.getAdminEmail());
        String corporateNumber = emptyToNull(requestVO.getCorporateNumber());
        String businessType = emptyToNull(requestVO.getBusinessType());
        String businessCategory = emptyToNull(requestVO.getBusinessCategory());

        // concurrent 등록 시 중복코드 충돌을 피하기 위해 제한된 횟수로 재시도한다.
        for (int attempt = 0; attempt < 5; attempt++) {
            String maxCode = factoryInfoDAO.selectMaxFactoryCode();

            String factoryCode = FactoryCodeGenerator.nextFactoryCode(maxCode);
            String tenantCode = "TENANT_" + factoryCode;

            try {
                factoryInfoDAO.insertFactory(
                        factoryCode,
                        factoryNm,
                        tenantCode,
                        adminEmail,
                        corporateNumber,
                        businessType,
                        businessCategory
                );

                FactoryRegistrationResultVO resultVO = new FactoryRegistrationResultVO();
                resultVO.setFactoryCode(factoryCode);
                resultVO.setFactoryNm(factoryNm);
                resultVO.setTenantCode(tenantCode);
                resultVO.setAdminEmail(adminEmail);
                resultVO.setCorporateNumber(corporateNumber);
                resultVO.setBusinessType(businessType);
                resultVO.setBusinessCategory(businessCategory);
                resultVO.setCreatedAt(Instant.now().toString());
                return resultVO;
            } catch (DuplicateKeyException ex) {
                // duplicate factory code generated by concurrent insert. retry.
            }
        }

        throw new IllegalStateException("Unable to generate unique factory code");
    }

    @Override
    public PlatformTenantDashboardResultVO listDashboardTenants(
            PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO condition = normalizeQuery(queryVO);

        int total = factoryInfoDAO.selectTenantCount(condition, null);
        int active = factoryInfoDAO.selectTenantCount(condition, "Y");
        int inactive = factoryInfoDAO.selectTenantCount(condition, "N");
        List<PlatformTenantDashboardItemVO> items = factoryInfoDAO.selectDashboardTenantItems(condition);

        PlatformTenantDashboardSummaryVO summary = new PlatformTenantDashboardSummaryVO();
        summary.setTotal(total);
        summary.setActive(active);
        summary.setInactive(inactive);

        PlatformTenantDashboardResultVO result = new PlatformTenantDashboardResultVO();
        result.setSummary(summary);
        result.setItems(items);
        return result;
    }

    @Override
    public List<SampleTenantVO> listRecentTenants(int limit) {
        return factoryInfoDAO.selectRecentTenants(limit);
    }

    private PlatformTenantDashboardQueryVO normalizeQuery(PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO normalized = new PlatformTenantDashboardQueryVO();
        if (queryVO == null) {
            return normalized;
        }

        normalized.setPageIndex(Math.max(0, queryVO.getPageIndex()));
        int pageSize = queryVO.getPageSize();
        if (pageSize <= 0) {
            pageSize = 10;
        }
        if (pageSize > 100) {
            pageSize = 100;
        }
        normalized.setPageSize(pageSize);
        normalized.setSearchField(emptyToNull(queryVO.getSearchField()));
        normalized.setSearchKeyword(emptyToNull(queryVO.getSearchKeyword()));
        normalized.setStatus(emptyToNull(queryVO.getStatus()) == null ? "all" : queryVO.getStatus().trim());
        return normalized;
    }

    private void validateRequest(FactoryRegistrationRequestVO requestVO) {
        if (requestVO == null || requestVO.getFactoryNm() == null || requestVO.getFactoryNm().trim().isEmpty()) {
            throw new IllegalArgumentException("factoryNm is required");
        }
    }

    private String emptyToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

}
