package egovframework.let.platforms.tenants.service.impl;

import java.time.Instant;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardItemVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardQueryVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardResultVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardSummaryVO;
import egovframework.let.platforms.tenants.domain.model.SampleTenantVO;
import egovframework.let.platforms.tenants.domain.model.TenantRegistrationRequestVO;
import egovframework.let.platforms.tenants.domain.model.TenantRegistrationResultVO;
import egovframework.let.platforms.tenants.domain.repository.TenantInfoDAO;
import egovframework.let.platforms.tenants.service.PlatformTenantService;

/**
 * 플랫폼 테넌트 서비스 구현체
 */
@Service("platformTenantService")
public class PlatformTenantServiceImpl implements PlatformTenantService {

    @Resource(name = "tenantInfoDAO")
    private TenantInfoDAO tenantInfoDAO;

    @Override
    @Transactional
    public TenantRegistrationResultVO registerTenant(TenantRegistrationRequestVO requestVO) {
        validateRequest(requestVO);

        String tenantNm = requestVO.getTenantNm().trim();
        String adminEmail = emptyToNull(requestVO.getAdminEmail());
        String corporateNumber = emptyToNull(requestVO.getCorporateNumber());
        String businessType = emptyToNull(requestVO.getBusinessType());
        String businessCategory = emptyToNull(requestVO.getBusinessCategory());

        for (int attempt = 0; attempt < 5; attempt++) {
            String maxCode = tenantInfoDAO.selectMaxTenantCode();

            String tenantSerialCode = TenantCodeGenerator.nextTenantCode(maxCode);
            String tenantCode = "TENANT_" + tenantSerialCode;

            try {
                tenantInfoDAO.insertTenant(
                        tenantSerialCode,
                        tenantNm,
                        adminEmail,
                        corporateNumber,
                        businessType,
                        businessCategory
                );

                TenantRegistrationResultVO resultVO = new TenantRegistrationResultVO();
                resultVO.setTenantId(tenantInfoDAO.selectTenantIdByCode(tenantCode));
                resultVO.setTenantCode(tenantCode);
                resultVO.setTenantNm(tenantNm);
                resultVO.setAdminEmail(adminEmail);
                resultVO.setCorporateNumber(corporateNumber);
                resultVO.setBusinessType(businessType);
                resultVO.setBusinessCategory(businessCategory);
                resultVO.setCreatedAt(Instant.now().toString());
                return resultVO;
            } catch (DuplicateKeyException ex) {
                // duplicate code generated by concurrent insert. retry.
            }
        }

        throw new IllegalStateException("Unable to generate unique tenant code");
    }

    @Override
    public PlatformTenantDashboardResultVO listDashboardTenants(
            PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO condition = normalizeQuery(queryVO);

        int total = tenantInfoDAO.selectTenantCount(condition, null);
        int active = tenantInfoDAO.selectTenantCount(condition, "Y");
        int inactive = tenantInfoDAO.selectTenantCount(condition, "N");
        List<PlatformTenantDashboardItemVO> items = tenantInfoDAO.selectDashboardTenantItems(condition);

        PlatformTenantDashboardSummaryVO summary = new PlatformTenantDashboardSummaryVO();
        summary.setTotal(total);
        summary.setActive(active);
        summary.setInactive(inactive);

        PlatformTenantDashboardResultVO result = new PlatformTenantDashboardResultVO();
        result.setSummary(summary);
        result.setItems(items);
        return result;
    }

    @Override
    public List<SampleTenantVO> listRecentTenants(int limit) {
        return tenantInfoDAO.selectRecentTenants(limit);
    }

    private PlatformTenantDashboardQueryVO normalizeQuery(PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO normalized = new PlatformTenantDashboardQueryVO();
        if (queryVO == null) {
            return normalized;
        }

        normalized.setPageIndex(Math.max(0, queryVO.getPageIndex()));
        int pageSize = queryVO.getPageSize();
        if (pageSize <= 0) {
            pageSize = 10;
        }
        if (pageSize > 100) {
            pageSize = 100;
        }
        normalized.setPageSize(pageSize);
        normalized.setSearchField(emptyToNull(queryVO.getSearchField()));
        normalized.setSearchKeyword(emptyToNull(queryVO.getSearchKeyword()));
        normalized.setStatus(emptyToNull(queryVO.getStatus()) == null ? "all" : queryVO.getStatus().trim());
        return normalized;
    }

    private void validateRequest(TenantRegistrationRequestVO requestVO) {
        if (requestVO == null || requestVO.getTenantNm() == null || requestVO.getTenantNm().trim().isEmpty()) {
            throw new IllegalArgumentException("tenantNm is required");
        }
    }

    private String emptyToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
