package egovframework.let.platforms.tenants.service.impl;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.regex.Pattern;

import javax.annotation.Resource;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardItemVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardQueryVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardResultVO;
import egovframework.let.platforms.tenants.domain.model.PlatformTenantDashboardSummaryVO;
import egovframework.let.platforms.tenants.domain.model.SampleTenantVO;
import egovframework.let.platforms.tenants.domain.model.TenantRegistrationRequestVO;
import egovframework.let.platforms.tenants.domain.model.TenantRegistrationResultVO;
import egovframework.let.platforms.tenants.domain.repository.TenantInfoDAO;
import egovframework.let.platforms.tenants.service.PlatformTenantService;

/**
 * 플랫폼 테넌트 서비스 구현체
 */
@Service("platformTenantService")
public class PlatformTenantServiceImpl implements PlatformTenantService {

    private static final DateTimeFormatter TENANT_CODE_DATE_FORMATTER = DateTimeFormatter.ofPattern("yyMMdd");
    private static final ZoneId BUSINESS_ZONE = ZoneId.of("Asia/Seoul");
    private static final Pattern EMAIL_PATTERN =
            Pattern.compile("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");

    @Resource(name = "tenantInfoDAO")
    private TenantInfoDAO tenantInfoDAO;

    @Override
    @Transactional
    public TenantRegistrationResultVO registerTenant(TenantRegistrationRequestVO requestVO) {
        validateRequest(requestVO);

        String tenantNm = requestVO.getTenantNm().trim();
        String adminEmail = emptyToNull(requestVO.getAdminEmail());
        String corporateNumber = emptyToNull(requestVO.getCorporateNumber());
        String businessType = emptyToNull(requestVO.getBusinessType());
        String businessCategory = emptyToNull(requestVO.getBusinessCategory());

        for (int attempt = 0; attempt < 5; attempt++) {
            String datePrefix = TENANT_CODE_DATE_FORMATTER.format(LocalDate.now(BUSINESS_ZONE));
            String maxCodeForDate = tenantInfoDAO.selectMaxTenantCodeByDatePrefix(datePrefix);

            String tenantSerialCode = TenantCodeGenerator.nextTenantCode(datePrefix, maxCodeForDate);
            String tenantCode = "TENANT_" + tenantSerialCode;

            try {
                tenantInfoDAO.insertTenant(
                        tenantSerialCode,
                        tenantNm,
                        adminEmail,
                        corporateNumber,
                        businessType,
                        businessCategory
                );

                TenantRegistrationResultVO resultVO = new TenantRegistrationResultVO();
                resultVO.setTenantId(tenantInfoDAO.selectTenantIdByCode(tenantSerialCode));
                resultVO.setTenantCode(tenantCode);
                resultVO.setTenantNm(tenantNm);
                resultVO.setAdminEmail(adminEmail);
                resultVO.setCorporateNumber(corporateNumber);
                resultVO.setBusinessType(businessType);
                resultVO.setBusinessCategory(businessCategory);
                resultVO.setCreatedAt(Instant.now().toString());
                return resultVO;
            } catch (DuplicateKeyException ex) {
                // duplicate code generated by concurrent insert. retry.
            }
        }

        throw new IllegalStateException("Unable to generate unique tenant code");
    }

    @Override
    @Transactional
    public void updateOnboardingStatusByTenantCode(String tenantCode, String onboardingStatus) {
        String normalizedTenantCode = normalizeStorageTenantCode(tenantCode);
        String normalizedOnboardingStatus = normalizeOnboardingTransitionStatus(onboardingStatus);
        tenantInfoDAO.updateOnboardingStatusByTenantCode(normalizedTenantCode, normalizedOnboardingStatus);
    }

    @Override
    public PlatformTenantDashboardResultVO listDashboardTenants(
            PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO condition = normalizeQuery(queryVO);

        int total = tenantInfoDAO.selectTenantCount(condition, null);
        int active = tenantInfoDAO.selectTenantCount(condition, "Y");
        int inactive = tenantInfoDAO.selectTenantCount(condition, "N");
        List<PlatformTenantDashboardItemVO> items = tenantInfoDAO.selectDashboardTenantItems(condition);

        PlatformTenantDashboardSummaryVO summary = new PlatformTenantDashboardSummaryVO();
        summary.setTotal(total);
        summary.setActive(active);
        summary.setInactive(inactive);

        PlatformTenantDashboardResultVO result = new PlatformTenantDashboardResultVO();
        result.setSummary(summary);
        result.setItems(items);
        return result;
    }

    @Override
    public List<SampleTenantVO> listRecentTenants(int limit) {
        return tenantInfoDAO.selectRecentTenants(limit);
    }

    private PlatformTenantDashboardQueryVO normalizeQuery(PlatformTenantDashboardQueryVO queryVO) {
        PlatformTenantDashboardQueryVO normalized = new PlatformTenantDashboardQueryVO();
        if (queryVO == null) {
            return normalized;
        }

        normalized.setPageIndex(Math.max(0, queryVO.getPageIndex()));
        int pageSize = queryVO.getPageSize();
        if (pageSize <= 0) {
            pageSize = 10;
        }
        if (pageSize > 100) {
            pageSize = 100;
        }
        normalized.setPageSize(pageSize);
        normalized.setSearchField(emptyToNull(queryVO.getSearchField()));
        normalized.setSearchKeyword(emptyToNull(queryVO.getSearchKeyword()));
        normalized.setStatus(normalizeUseStatus(queryVO.getStatus()));
        normalized.setOnboardingStatus(normalizeOnboardingStatus(queryVO.getOnboardingStatus()));
        return normalized;
    }

    private String normalizeUseStatus(String status) {
        String normalized = emptyToNull(status);
        if (normalized == null) {
            return "all";
        }

        String upper = normalized.toUpperCase();
        if ("ACTIVE".equals(upper)
                || "INACTIVE".equals(upper)
                || "ALL".equals(upper)) {
            return upper;
        }

        return "all";
    }

    private String normalizeOnboardingStatus(String onboardingStatus) {
        String normalized = emptyToNull(onboardingStatus);
        if (normalized == null) {
            return "all";
        }

        String upper = normalized.toUpperCase();
        if ("EMAIL_QUEUED".equals(upper)
                || "EMAIL_SENT".equals(upper)
                || "EMAIL_VERIFIED".equals(upper)
                || "FIRST_SETUP_COMPLETED".equals(upper)
                || "ACTIVE".equals(upper)
                || "ALL".equals(upper)) {
            return upper;
        }

        return "all";
    }

    private String normalizeOnboardingTransitionStatus(String onboardingStatus) {
        String normalized = emptyToNull(onboardingStatus);
        if (normalized == null) {
            throw new IllegalArgumentException("onboardingStatus is required");
        }

        String upper = normalized.toUpperCase();
        if ("EMAIL_QUEUED".equals(upper)
                || "EMAIL_SENT".equals(upper)
                || "EMAIL_VERIFIED".equals(upper)
                || "FIRST_SETUP_COMPLETED".equals(upper)
                || "ACTIVE".equals(upper)) {
            return upper;
        }

        throw new IllegalArgumentException("unsupported onboardingStatus");
    }

    private String normalizeStorageTenantCode(String tenantCode) {
        String normalized = emptyToNull(tenantCode);
        if (normalized == null) {
            throw new IllegalArgumentException("tenantCode is required");
        }
        if (normalized.startsWith("TENANT_")) {
            return normalized.substring("TENANT_".length());
        }
        return normalized;
    }

    private void validateRequest(TenantRegistrationRequestVO requestVO) {
        if (requestVO == null || requestVO.getTenantNm() == null || requestVO.getTenantNm().trim().isEmpty()) {
            throw new IllegalArgumentException("tenantNm is required");
        }
        if (requestVO.getCorporateNumber() == null || requestVO.getCorporateNumber().trim().isEmpty()) {
            throw new IllegalArgumentException("corporateNumber is required");
        }
        if (requestVO.getBusinessType() == null || requestVO.getBusinessType().trim().isEmpty()) {
            throw new IllegalArgumentException("businessType is required");
        }
        if (requestVO.getBusinessCategory() == null || requestVO.getBusinessCategory().trim().isEmpty()) {
            throw new IllegalArgumentException("businessCategory is required");
        }
        String adminEmail = requestVO.getAdminEmail();
        if (adminEmail == null || adminEmail.trim().isEmpty()) {
            throw new IllegalArgumentException("adminEmail is required");
        }
        if (!EMAIL_PATTERN.matcher(adminEmail.trim()).matches()) {
            throw new IllegalArgumentException("adminEmail format is invalid");
        }
    }

    private String emptyToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
