ALTER TABLE tb_tenant
ADD COLUMN IF NOT EXISTS onboarding_status VARCHAR(50) NOT NULL DEFAULT 'EMAIL_QUEUED';

COMMENT ON COLUMN tb_tenant.onboarding_status IS '온보딩 상태(EMAIL_QUEUED, EMAIL_SENT, EMAIL_VERIFIED, FIRST_SETUP_COMPLETED, ACTIVE)';
